version: '3.8'

services:
  web:
    image: edisontsang/my-web-app:latest  # verandering opdracht3
    ports:
      - "8080:80" 
    volumes:
      - .:/var/www/html
    depends_on:
      - db

  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cloudsystemenDB
      MYSQL_USER: EdisonT
      MYSQL_PASSWORD: EDI123
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:

